In [1]:
%reload_ext autoreload
%autoreload 2
%matplotlib inline

In [2]:
from fastai import *
from fastai.text import *

In [3]:
bs = 64

In [6]:
path = untar_data(URLs.IMDB_SAMPLE)
path.ls()

[PosixPath('/Users/ricardofernandez/.fastai/data/imdb_sample/texts.csv')]

In [7]:
!head /Users/ricardofernandez/.fastai/data/imdb_sample/texts.csv

label,text,is_valid
negative,"Un-bleeping-believable! Meg Ryan doesn't even look her usual pert lovable self in this, which normally makes me forgive her shallow ticky acting schtick. Hard to believe she was the producer on this dog. Plus Kevin Kline: what kind of suicide trip has his career been on? Whoosh... Banzai!!! Finally this was directed by the guy who did Big Chill? Must be a replay of Jonestown - hollywood style. Wooofff!",False
positive,"This is a extremely well-made film. The acting, script and camera-work are all first-rate. The music is good, too, though it is mostly early in the film, when things are still relatively cheery. There are no really superstars in the cast, though several faces will be familiar. The entire cast does an excellent job with the script.<br /><br />But it is hard to watch, because there is no good end to a situation like the one presented. It is now fashionable to blame the British for setting Hindus and Muslims against each other, and then cruelly

In [8]:
data_lm = TextDataBunch.from_csv(path, 'texts.csv')

In [9]:
data_lm

TextClasDataBunch;

Train: LabelList (799 items)
x: TextList
xxbos i have just lost three hours of my life to this travesty , and i can honestly say i feel violated . i had read the reviews and heard the warnings , and i thought i was prepared for anything - at best i thought , a faithful ( if misguided ) attempt at an original adaptation ; at worst , a so - good - xxunk - bad " xxmaj plan 9 " for the new millennium . xxmaj so when i managed to pick up a copy in xxmaj walmart while in xxmaj florida and brought it back to the xxup uk , i joked to my friends " xxmaj prepare for the worst movie ever made ! " xxmaj oh , cruel xxmaj karma . xxmaj there is absolutely xxup nothing to recommend this film . xxmaj the " special " effects look like the work of a first year design student using a xxmaj xxunk xxup xxunk . xxmaj the acting is terrible , the accents are xxup worse than terrible ( one artillery xxunk ' accent seems to take us on a tour of the xxmaj british xxmaj xxunk , from xxmaj sco

In [12]:
data_lm.x

TextList (799 items)
xxbos i have just lost three hours of my life to this travesty , and i can honestly say i feel violated . i had read the reviews and heard the warnings , and i thought i was prepared for anything - at best i thought , a faithful ( if misguided ) attempt at an original adaptation ; at worst , a so - good - xxunk - bad " xxmaj plan 9 " for the new millennium . xxmaj so when i managed to pick up a copy in xxmaj walmart while in xxmaj florida and brought it back to the xxup uk , i joked to my friends " xxmaj prepare for the worst movie ever made ! " xxmaj oh , cruel xxmaj karma . xxmaj there is absolutely xxup nothing to recommend this film . xxmaj the " special " effects look like the work of a first year design student using a xxmaj xxunk xxup xxunk . xxmaj the acting is terrible , the accents are xxup worse than terrible ( one artillery xxunk ' accent seems to take us on a tour of the xxmaj british xxmaj xxunk , from xxmaj scotland to xxmaj xxunk via xxmaj xxunk xxm

In [13]:
data_lm.vocab.itos[:10]

['xxunk',
 'xxpad',
 'xxbos',
 'xxeos',
 'xxfld',
 'xxmaj',
 'xxup',
 'xxrep',
 'xxwrep',
 'the']

In [14]:
data_lm.train_ds[0][0]

Text xxbos i have just lost three hours of my life to this travesty , and i can honestly say i feel violated . i had read the reviews and heard the warnings , and i thought i was prepared for anything - at best i thought , a faithful ( if misguided ) attempt at an original adaptation ; at worst , a so - good - xxunk - bad " xxmaj plan 9 " for the new millennium . xxmaj so when i managed to pick up a copy in xxmaj walmart while in xxmaj florida and brought it back to the xxup uk , i joked to my friends " xxmaj prepare for the worst movie ever made ! " xxmaj oh , cruel xxmaj karma . xxmaj there is absolutely xxup nothing to recommend this film . xxmaj the " special " effects look like the work of a first year design student using a xxmaj xxunk xxup xxunk . xxmaj the acting is terrible , the accents are xxup worse than terrible ( one artillery xxunk ' accent seems to take us on a tour of the xxmaj british xxmaj xxunk , from xxmaj scotland to xxmaj xxunk via xxmaj xxunk xxmaj ireland ) , t

In [18]:
x, y = next(iter(data_lm.train_dl))

In [21]:
x.shape, y.shape

(torch.Size([64, 1704]), torch.Size([64]))

In [22]:
data_lm.train_ds[0][0].data[:10]

array([  2,  19,  40,  60, 394, 296, 628,  14,  79, 135])

##  Using data block

In [28]:
data = (TextList.from_csv(path, 'texts.csv', cols='text')
                .split_from_df(col=2)
                .label_from_df(cols=0)
                .databunch())

In [29]:
data

TextClasDataBunch;

Train: LabelList (800 items)
x: TextList
xxbos xxmaj un - xxunk - believable ! xxmaj meg xxmaj ryan does n't even look her usual xxunk lovable self in this , which normally makes me forgive her shallow xxunk acting xxunk . xxmaj hard to believe she was the producer on this dog . xxmaj plus xxmaj kevin xxmaj kline : what kind of suicide trip has his career been on ? xxmaj xxunk ... xxmaj xxunk ! ! ! xxmaj finally this was directed by the guy who did xxmaj big xxmaj xxunk ? xxmaj must be a replay of xxmaj jonestown - hollywood style . xxmaj xxunk !,xxbos xxmaj this is a extremely well - made film . xxmaj the acting , script and camera - work are all first - rate . xxmaj the music is good , too , though it is mostly early in the film , when things are still relatively xxunk . xxmaj there are no really xxunk in the cast , though several faces will be familiar . xxmaj the entire cast does an excellent job with the script . 
 
  xxmaj but it is hard to watch , because the

## Language model 

In [30]:
path = untar_data(URLs.IMDB)
path.ls()

[PosixPath('/Users/ricardofernandez/.fastai/data/imdb/ld.pkl'),
 PosixPath('/Users/ricardofernandez/.fastai/data/imdb/test'),
 PosixPath('/Users/ricardofernandez/.fastai/data/imdb/ll_lm.pkl'),
 PosixPath('/Users/ricardofernandez/.fastai/data/imdb/tmp_clas'),
 PosixPath('/Users/ricardofernandez/.fastai/data/imdb/vocab_lm.pkl'),
 PosixPath('/Users/ricardofernandez/.fastai/data/imdb/imdb.vocab'),
 PosixPath('/Users/ricardofernandez/.fastai/data/imdb/unsup'),
 PosixPath('/Users/ricardofernandez/.fastai/data/imdb/README'),
 PosixPath('/Users/ricardofernandez/.fastai/data/imdb/tmp_lm'),
 PosixPath('/Users/ricardofernandez/.fastai/data/imdb/ll_clas.pkl'),
 PosixPath('/Users/ricardofernandez/.fastai/data/imdb/train')]

In [31]:
(path/'train').ls()

[PosixPath('/Users/ricardofernandez/.fastai/data/imdb/train/neg'),
 PosixPath('/Users/ricardofernandez/.fastai/data/imdb/train/pos'),
 PosixPath('/Users/ricardofernandez/.fastai/data/imdb/train/unsupBow.feat'),
 PosixPath('/Users/ricardofernandez/.fastai/data/imdb/train/labeledBow.feat')]

## Creating the TextLMDataBunch

In [32]:
path.ls()

[PosixPath('/Users/ricardofernandez/.fastai/data/imdb/ld.pkl'),
 PosixPath('/Users/ricardofernandez/.fastai/data/imdb/test'),
 PosixPath('/Users/ricardofernandez/.fastai/data/imdb/ll_lm.pkl'),
 PosixPath('/Users/ricardofernandez/.fastai/data/imdb/tmp_clas'),
 PosixPath('/Users/ricardofernandez/.fastai/data/imdb/vocab_lm.pkl'),
 PosixPath('/Users/ricardofernandez/.fastai/data/imdb/imdb.vocab'),
 PosixPath('/Users/ricardofernandez/.fastai/data/imdb/unsup'),
 PosixPath('/Users/ricardofernandez/.fastai/data/imdb/README'),
 PosixPath('/Users/ricardofernandez/.fastai/data/imdb/tmp_lm'),
 PosixPath('/Users/ricardofernandez/.fastai/data/imdb/ll_clas.pkl'),
 PosixPath('/Users/ricardofernandez/.fastai/data/imdb/train')]

In [33]:
data_lm = (TextList.from_folder(path)
           #Inputs: all the text files in path
            .filter_by_folder(include=['train', 'test', 'unsup']) 
           #We may have other temp folders that contain text files so we only keep what's in train and test
            .split_by_rand_pct(0.1, seed=42)
           #We randomly split and keep 10% (10,000 reviews) for validation
            .label_for_lm()           
           #We want to do a language model so we label accordingly
            .databunch(bs=bs, num_workers=1))

In [34]:
len(data_lm.vocab.itos), len(data_lm.train_ds)

(60000, 90000)

In [35]:
data_lm.show_batch()

In [36]:
data_lm.save('lm_databunch')

## Loading saved data, and creating the language model

In [37]:
data_lm = load_data(path, 'lm_databunch', bs=bs)

In [41]:
learn_lm = language_model_learner(data_lm, AWD_LSTM, drop_mult=0.3)

In [47]:
# grab vocab from trained model
wiki_itos = pickle.load(open(Config().model_path()/'wt103-fwd/itos_wt103.pkl', 'rb'))

In [49]:
wiki_itos[:10]

['xxunk',
 'xxpad',
 'xxbos',
 'xxeos',
 'xxfld',
 'xxmaj',
 'xxup',
 'xxrep',
 'xxwrep',
 'the']

In [50]:
vocab = data_lm.vocab

In [52]:
vocab.itos[:10]

['xxunk',
 'xxpad',
 'xxbos',
 'xxeos',
 'xxfld',
 'xxmaj',
 'xxup',
 'xxrep',
 'xxwrep',
 'the']

In [53]:
vocab.stoi['stingray']

37367

In [54]:
vocab.itos[vocab.stoi['stingray']]

'stingray'

In [55]:
vocab.itos[vocab.stoi['mobula']]

'xxunk'

In [58]:
awd = learn_lm.model[0]

In [57]:
from scipy.spatial.distance import cosine as dist

In [61]:
enc = learn_lm.model[0].encoder  # first layer is embedding

In [62]:
enc

Embedding(60000, 400, padding_idx=1)

In [64]:
enc.weight.size() # our vocab is 60000 words and we embedd them in a 400 dim space

torch.Size([60000, 400])

## Difference in vocabulary between IMDB and Wikipedia

In [67]:
len(wiki_itos) # wiki text

60000

In [68]:
len(vocab.itos) # imbd text

60000

In [72]:
i, unks = 0, []
while len(unks) < 50:
    if data_lm.vocab.itos[i] not in wiki_itos:
        unks.append((i,data_lm.vocab.itos[i]))
    i += 1

In [76]:
unks[:10]

[(36, "n't"),
 (162, "'ve"),
 (170, "'m"),
 (526, '\x96'),
 (953, 'imdb'),
 (1680, '\x85 '),
 (1785, '\x85'),
 (2011, 'crappy'),
 (2693, 'seagal'),
 (2876, '---')]

In [77]:
wiki_words = set(wiki_itos)

In [78]:
imdb_words = set(vocab.itos)

In [79]:
wiki_not_imdb = wiki_words.difference(imdb_words)
imdb_not_wiki = imdb_words.difference(wiki_words)

In [80]:
set([1,2,3]).difference(set([3,4,5]))

{1, 2}

In [82]:
wiki_not_imdb_list = []

for i in range(100):
    word = wiki_not_imdb.pop()
    wiki_not_imdb_list.append(word)
    wiki_not_imdb.add(word)

In [83]:
wiki_not_imdb_list[:15]

['i-94',
 'kennebec',
 'republished',
 'ucf',
 'burh',
 'felice',
 'weald',
 'appellant',
 'wallenberg',
 'brookwood',
 'pwi',
 'restrengthening',
 'conscription',
 'extinctions',
 'genotype']

In [84]:
imdb_not_wiki_list = []

for i in range(100):
    word = imdb_not_wiki.pop()
    imdb_not_wiki_list.append(word)
    imdb_not_wiki.add(word)

In [85]:
imdb_not_wiki_list[:15]

['bodysnatchers',
 'foregoing',
 'boppers',
 'cots',
 'lurks',
 'populism',
 'lohman',
 'plasticized',
 'midian',
 'dropouts',
 'couleurs',
 'vlady',
 'tellers',
 'climaxing',
 'vaccaro']

All words that appear in the IMDB vocab, but not the wikitext-103 vocab, will be initialized to the same random vector in a model. As the model trains, we will learn these weights.

In [89]:
vocab.stoi["modernisation"], vocab.itos[vocab.stoi["modernisation"]]

(0, 'xxunk')

In [87]:
"modernisation" in wiki_words

True

In [88]:
vocab.stoi["30-something"]

26862

In [90]:
"30-something" in wiki_words, "30-something" in imdb_words

(False, True)

In [93]:
vocab.stoi["linklater"]

16591

In [94]:
"linklater" in wiki_words, "linklater" in imdb_words

(False, True)

In [91]:
"house" in wiki_words, "house" in imdb_words

(True, True)

In [98]:
vocab.stoi["30-something"], vocab.stoi["linklater"]

(26862, 16591)

In [92]:
# so linklater and house are in imdb but not in wiki, they
np.allclose(enc.weight[vocab.stoi["30-something"], :], 
            enc.weight[vocab.stoi["linklater"], :])

True

In [99]:
np.allclose(enc.weight[vocab.stoi["30-something"], :], 
            enc.weight[vocab.stoi["house"], :])

False

### Generating fake movie reviews (using wiki-text model)

In [108]:
TEXT = "The color of the sky is"
N_WORDS = 40
N_SENTENCES = 2

In [109]:
print("\n".join(learn_lm.predict(TEXT, N_WORDS, temperature=0.75) for _ in range(N_SENTENCES)))

The color of the sky is created by a color of skin ( such as yellow , blue , and red ) , which is also used to represent the flesh . The skin is generally left to paint on the sides , with blue
The color of the sky is a dark blue , a dark blue ( which is white and blue ) , and the surface is brown ( orange ) . The blue , orange and green surfaces show a variety of colours and the number


In [113]:
learn_lm.predict(TEXT, 2)

'The color of the sky is used by'

In [116]:
learn_lm.data.one_item("The color of the sky")[0].shape

torch.Size([1, 7])

In [123]:
learn_lm.data.one_item("The color")[0]

tensor([[   2,    5,    9, 1424]])

In [121]:
learn_lm.predict??

In [120]:
learn_lm.model.reset??

In [137]:
xb, _ = learn_lm.data.one_item("the the")

In [138]:
xb

tensor([[2, 9, 9]])

In [140]:
xb.new_tensor([5])[None]

tensor([[5]])

In [141]:
TEXT = "I hated this movie"
N_WORDS = 30
N_SENTENCES = 2

In [142]:
print("\n".join(learn_lm.predict(TEXT, N_WORDS, temperature=0.75) for _ in range(N_SENTENCES)))

I hated this movie ( The Legend of Zelda : Awakening ) . Several years after the film 's release , controversy emerged in United States
I hated this movie by Stanley Baldwin . He wrote , " i don ' t care that something , even though i do have a science fiction , you know


In [143]:
print("\n".join(learn_lm.predict(TEXT, N_WORDS, temperature=0.75) for _ in range(N_SENTENCES)))

I hated this movie by American film director John F. Kennedy . In the 1997 film The Lord of the Banner , Kennedy refers to
I hated this movie for its content and make - up , writing , " i don ' t think that i wanted to do it . i was saying it 's not a


In [144]:
doc(LanguageLearner.predict)

In [145]:
print("\n".join(learn_lm.predict(TEXT, N_WORDS, temperature=0.10) for _ in range(N_SENTENCES)))

I hated this movie by John Lennon , and he said , " i ' m not sure what i ' m doing . It 's not a bad thing .
I hated this movie by John Lennon , and he said he was " a fan of the Beatles " . He said that he was " very proud of


In [146]:
doc(LanguageLearner.predict)

In [149]:
print("\n".join(learn_lm.predict(TEXT, N_WORDS, temperature=0.10) for _ in range(N_SENTENCES)))

I hated this movie by John Lennon , and it was a reference to the American film The Lord of the Rings . The film was also
I hated this movie by John Lennon , and he said that he was " a fan of the Beatles " . He also said that he was " very


In [153]:
learn_lm.predict??

In [152]:
torch.Tensor([0.2, 0.1, 0.7])**(1/0.1)

tensor([1.0240e-07, 1.0000e-10, 2.8248e-02])

### Training the model

In [154]:
learn_lm.lr_find()

LR Finder is complete, type {learner_name}.recorder.plot() to see the graph.


KeyboardInterrupt: 